#!/bin/sh

set -e

PACKAGE=$(sed -ne '/^Package:/{s/Package:[[:space:]][[:space:]]*//p;q}' VERSION)
VERSION=$(sed -ne '/^Version:/{s/Version:[[:space:]][[:space:]]*//p;q}' VERSION)

if [ -z "$PACKAGE" ] || [ -z "$VERSION" ]; then
  echo "Error parsing package name and version from VERSION"
  exit 1
fi

git archive --verbose --prefix="${PACKAGE}-${VERSION}/" "release/${PACKAGE}-${VERSION}" \
	| xz --compress --to-stdout > ../${PACKAGE}-${VERSION}.tar.xz

echo "Finished creating ../${PACKAGE}-${VERSION}.tar.xz" >&2
