name: Build Debian Package

on:
  push:
    branches:
      - ubuntu/devel

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: sbuild-outer/sbuild
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper dh-make dh-python
        sudo apt-get install -y libexception-class-perl libfilesys-df-perl libmime-lite-perl libyaml-tiny-perl python3-all
        
    - name: Build package
      run: |
        cd sbuild-outer/sbuild
        ls -al
        dpkg-buildpackage -us -uc
        pwd
        
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: /home/runner/work/sbuild-ubuntu/sbuild-ubuntu/sbuild-outer/sbuild-outer/*.deb  # adjust path to the Debian package
